### ISSUE TITLE
I have error :(

### ISSUE THREAD

**Issue by MrFallen** [pvtl/voyager-page-blocks#10]
`C:\Users\MrFallen\AppData\Roaming\Composer\2fe>php artisan voyager-page-blocks:install
Publishing Page Blocks assets, database, and config files
Copied Directory [\vendor\pvtl\voyager-page-blocks\config] To [\config]
Publishing complete.
Dumping the autoloaded files and reloading all new files
Migrating the database tables into your application
Nothing to migrate.
Seeding data into the database

   Illuminate\Database\Eloquent\ModelNotFoundException  : No query results for model [Pvtl\VoyagerPages\Page].

  at C:\Users\MrFallen\AppData\Roaming\Composer\2fe\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:414
    410|         if (! is_null($model = $this->first($columns))) {
    411|             return $model;
    412|         }
    413|
  > 414|         throw (new ModelNotFoundException)->setModel(get_class($this->model));
    415|     }
    416|
    417|     /**
    418|      * Execute the query and get the first result or call a callback.

  Exception trace:

  1   Illuminate\Database\Eloquent\Builder::firstOrFail()
      C:\Users\MrFallen\AppData\Roaming\Composer\2fe\vendor\pvtl\voyager-page-blocks\database\seeds\PageBlocksTableSeeder.php:28

  2   PageBlocksTableSeeder::run()
      C:\Users\MrFallen\AppData\Roaming\Composer\2fe\vendor\tcg\voyager\src\Traits\Seedable.php:13

  Please use the argument -v to see more details.`

**Comment by lukewmoore** [comment]
Hi @MrFallen, this has been addressed in 0.8.3, including for existing voyager frontend sites. For new builds, follow the [installation instructions](https://github.com/pvtl/voyager-frontend#installation) before installing page blocks.
