### ISSUE TITLE
Error after installing page-blocks

### ISSUE THREAD

**Issue by adrienne** [pvtl/voyager-page-blocks#11]
When i try to navigate to Pages after installing page-blocks, i get the following error:

![image](https://user-images.githubusercontent.com/89705/46928787-0e5f6180-cff1-11e8-85db-69a69524be18.png)

It looks like it really is missing the route. When i add the following to the `/vendor/pvtl/voyager-page-blocks/routes/web.php` file at line 14, it works: 

```
Route::post('edit', ['uses' => "PageBlockController@edit", 'as' => 'edit']);
```

**Comment by lukewmoore** [comment]
Hey @adrienne, this can be caused if BREAD isn't created in Voyager, running `php artisan voyager-page-blocks:install` after installing via composer should prevent this from happening. But let us know if this wasn't the case.
