### ISSUE TITLE
How to add a block inside another block?

### ISSUE THREAD

**Issue by adrian-ub** [pvtl/voyager-page-blocks#13]
I have tried to add a block inside another block, but I have not managed to achieve it, can someone instruct me how to do it?

Thank you for having developed this package

**Comment by lukewmoore** [comment]
@adrian-ub This isn't functionality that Voyager Page Blocks supports. You may be able to create your own block to achieve a similar result to what you're after, [see more here](https://github.com/pvtl/voyager-page-blocks#creating--modifying-blocks).
