### ISSUE TITLE
Dynamic Slider-Block - Help

### ISSUE THREAD

**Issue by rubcubxyz** [pvtl/voyager-page-blocks#16]
I'm new at Laravel and I'm testing at the moment. And its actually really nice. But now I've got a problem and I don't have a clue how to solve it.

**What I did:**

1. Installed Laravel 5.7
2. Installed Voyager
3. Installed Voyager Frontend
4. Installed Voyager Blocks

Now i created my own Block. I want to create an block to display an dynamic slider.

Inside my Page in my Backend it looks actually like this: http://nimb.ws/gp1WkX 

For this my Code inside the /config/page-blocks.php looks like: http://nimb.ws/XVzyCN
And you can see i create 6 instances (manually) inside the slider block.

My Output inside the "dynamic_slider.blade.php" look like this: http://nimb.ws/N8ovGD and there is nothing dynamical.

**What I want to do:**

I want only one instance in my block. With my Image, Title, Subtitle and Link for my Slide. So i can display one slider. Then i need an buttlon like "add Slide" - then i get one more "instance" to upload an image, title, subtitle, link. An so on...

I think I know how to output the loop but I cant figure out the step for my admin-block. I hope you guys can help me. 

Thanks alot!

**Comment by hossainmdawlad** [comment]
I am also thinking of addable fields... but it seems...there is no one to support or communicate...

**Comment by mcnamee** [comment]
We'd love to be able to assist with your specific project), however unfortunately we don't the capacity within an open source scenario. If you manage to build the feature, we'd love to review a merge a PR.

_(This is a question about a specific project, related to a feature not in this project and therefore better suited for StackOverflow)_

All the best with your project/s
