### ISSUE TITLE
Inactive pages

### ISSUE THREAD

**Issue by Lumenate** [pvtl/voyager-page-blocks#17]
Hello, i have an issue when the "INACTIVE" option in Pages, it's simply ignored while pulling the post with the slug, there could be a workaround for this, just do this.
`$page = Page::where(['slug' => $slug, 'status' => 'ACTIVE'])->firstOrFail();`
Or maybe i can somehow alter the controller and use it instead of standard one?
Can someone please address this issue?

**Comment by mcnamee** [comment]
Hi @Lumenate Great find - thank you! Can you please submit a PR to address the issue?

**Comment by Liam-PVTL** [comment]
I've applied this change to both this and the pvtl/voyager-pages repos.
