### ISSUE TITLE
What happens when you have been overridden model ? such as Page, Category!!!

### ISSUE THREAD

**Issue by reksmeysrey** [pvtl/voyager-page-blocks#18]

**Comment by mcnamee** [comment]
Please provide more information on the issue you're experiencing - eg. expected outcome, what actually happens, environment, versions.

I'll reopen when adequate information has been provided

**Comment by reksmeysrey** [comment]
![screenshot-laravel58 love-2019 03 24-21-19-13](https://user-images.githubusercontent.com/35394133/54880734-e0712980-4e7a-11e9-8e01-c9c13d27c229.png)

I think because of $fillable! So I need to override model!
