### ISSUE TITLE
Can't install --Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by steveadamsfixedit** [pvtl/voyager-page-blocks#19]
Laravel 5.7.28
Voyager 1.x-dev
DB MySQL 8.0.12

Invalid argument supplied for foreach() (View: vendor/pvtl/voyager-page-blocks/resources/views/vendor/voyager/page-blocks/edit-add.blade.php)

Line 96 of that file:

                                        <?php $__currentLoopData = $templates; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $path => $template): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                                            <option value="template|<?php echo e($path); ?>">
                                                <?php echo e($template['name']); ?>

**Comment by Liam-PVTL** [comment]
Please make sure you can see page-blocks.php under app/config. Did you run this:
`php artisan voyager-page-blocks: install` ? 

If you did and the file is still not published, manually register the app service provider (under config/app.php): 
`        /*
         * Package Service Providers...
         */
        Pvtl\VoyagerPageBlocks\Providers\PageBlocksServiceProvider::class,
`
then run 

`php artisan vendor:publish --tag=config`
