### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by mcnamee** [pvtl/voyager-page-blocks#2]
Caching a block currently only caches the DB request. This is only working for `template` type blocks.

It'd be ideal if caching a block, was optimised further to cache the output of the view (and implemented for both template and include type blocks).

**Comment by Jean-PierreGassin** [comment]
Implemented with [this commit](https://github.com/pvtl/voyager-page-blocks/commit/a0e42adb8a430622da859d90b9cefdaac3f3baf7).
