### ISSUE TITLE
Getting "mb_strtolower() expects parameter 1 to be string, array given" in Voyager with multilingual activated.

### ISSUE THREAD

**Issue by viaativaweb** [pvtl/voyager-page-blocks#20]
First at all, sorry about my english, this isn't my first language.

I'm new in Git too 😄 

Current, my system is using this packages:

laravel/laravel: v5.7.*
tcg/voyager: v1.1.10
pvtl/voyager-frontend: v0.8.5
pvtl/voyager-page-blocks: v0.8.5

and them when I changed the voyager to multilingual, i got this error:

![image](https://user-images.githubusercontent.com/48333625/54364398-95ba0b00-464b-11e9-980e-4bb7dbe30369.png)

after looking for the error, I found a possible solution (but maybe not the best) and I would like to share.

in the file "project/vendor/pvtl/voyager-page-blocks/src/Page.php" add in the function "toSearchableArray" the following code:

```PHP
        ...

        $array['page_blocks'] = implode(' ', array_flatten($pageBlocks));

        //Verify if exist the translations of Voyager Multilanguage
        if(isset($array['translations']) ){
            //If true, implode to array with space glue
            $array['translations'] = implode(' ', $array['translations']);
        }

        return $array;
```

But I do not know if it would be better to use the "unset" function or some other code.

thanks for the awesome packages!!!!

EDIT:

I tried to update a post, but it gave an array error, so I think the best thing to do is to use the "unset"

```PHP
        ...

        $array['page_blocks'] = implode(' ', array_flatten($pageBlocks));

        //Verify if exist the translations of Voyager Multilanguage
        if(isset($array['translations']) && is_array($array['translations'])){
            //unset the translations
            unset($array['translations']);
        }

        return $array;
```

**Comment by mcnamee** [comment]
Hi @viaativaweb
If you find a solution to this, please submit a PR with some details on how we can test.

**Comment by jetrodn** [comment]
This is how I resolved this issue. Created a model:

```
<?php

namespace App;

class Page extends \Pvtl\VoyagerPageBlocks\Page
{
    /**
     * Get the indexed data array for the model.
     *
     * @return array
     */
    public function toSearchableArray(): array
    {
        $fields = $this->toArray();
        return \Arr::only($fields, ['id', 'title', 'slug', 'body', 'excerpt', 'meta_description', 'status']);
    }
}
```
There are all fields (excluding `translations` field that is array) that needs to be indexed.

Added new database seeder with rewriting `model_name` in `data_types` table: 

```
 /**
     * Auto generated seed file.
     */
    public function run()
    {
        $dataType = $this->dataType('slug', 'pages');
        if (!$dataType->exists) {
            $dataType->fill([
                'name'                  => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural'   => 'Pages',
                'icon'                  => 'voyager-file-text',
                'model_name'            => 'App\\Page',
                'controller'            => '\\Pvtl\\VoyagerPageBlocks\\Http\\Controllers\\PageController',
                'generate_permissions'  => 1,
                'description'           => '',
            ])->save();
        }

        if ($dataType->exists) {
            $dataType->update([
                'model_name' => 'App\\Page',
                'controller' => '\\Pvtl\\VoyagerFrontend\\Http\\Controllers\\PageController',
            ]);
        }
    }

    protected function dataType($field, $for)
    {
        return DataType::firstOrNew([$field => $for]);
    }
```

But I got stuck with another problem. This package doesn't have `PageBlock` translations support, so make sure you don't need this functionality before you will start resolving this issue.

**Comment by Liam-PVTL** [comment]
Hi @jetrodn / @viaativaweb, 

When exactly are you getting this issue? I've enabled multilingual but pages seem to be loading fine. Alternatively, as @mcnamee suggested please provide a PR with info on how we could test.
