### ISSUE TITLE
Install issues - Currently running "pvtl/voyager-frontend": "^0.9.1",

### ISSUE THREAD

**Issue by DaveArm** [pvtl/voyager-page-blocks#21]
Problem 1
    - Installation request for pvtl/voyager-page-blocks ^0.8.7 -> satisfiable by pvtl/voyager-page-blocks[0.8.7].
    - pvtl/voyager-page-blocks 0.8.7 requires pvtl/voyager-frontend ~0.8.0 -> satisfiable by pvtl/voyager-frontend[0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5] but these conflict with your requirements or minimum-stability.

**Comment by tonybrown85** [comment]
I'm also experiencing the same issue as @DaveArm. If you're able to please take a look that would be much appreciated. Thank you.

**Comment by mcnamee** [comment]
Sorry @DaveArm and @tonybrown85 
It looks like a new release wasn't pushed. I've just tagged 0.8.8 which should solve this (i.e. ensures the latest Voyager Frontend is used).

Give it a try and let us know

CC @lukewmoore

**Comment by DaveArm** [comment]
@mcnamee  thanks for looking at this Matt, im now getting this message:
 
```
There are no commands defined in the "voyager-page-blocks" namespace.                                                                           
  Did you mean this?                                                     
      voyager-pages
```

**Comment by tonybrown85** [comment]
@mcnamee Appreciate you looking into this. That made no difference for me unfortunately. Getting the same error but with the newer version for page-blocks. 

- Installation request for pvtl/voyager-page-blocks ^0.8.8 -> satisfiable by pvtl/voyager-page-blocks[0.8.8].
- pvtl/voyager-page-blocks 0.8.7 requires pvtl/voyager-frontend ^0.8.5 -> satisfiable by pvtl/voyager-frontend[0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5] but these conflict with your requirements or minimum-stability.

I ran composer update to make sure everything is up to date. I also cleared composer's cache but made no difference. I ran composer show pvtl/voyager-frontend just to ensure 0.9.1 is loading, which it is. This is running in a xampp environment with php 7.2 if that helps?

**Comment by DaveArm** [comment]
Would reverting frontend down a version or two fix this do you think? Currently installed 0.9.1

**Comment by howdu** [comment]
Packagist for page-blocks hasn't been updated yet but you can downgrade: 
composer require pvtl/voyager-frontend:0.8.5

**Comment by mcnamee** [comment]
Sorry guys, I now understand the issue.

You may have seen that one of the `voyager-page-blocks` dependencies was `voyager-frontend` 0.8.5. So in your project, if you manually installed voyager-frontend latest - this error would appear because of the voyager-frontend version mismatch.

In anycase, I've just got a chance to test `voyager-page-blocks` with the latest `voyager-frontend` and it's working well, so updated `voyager-page-blocks` dependencies.

My project `composer.json` requirements look like this:

```
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0",
        "pvtl/voyager-frontend": "^0.9.1",
        "pvtl/voyager-page-blocks": "^0.8.9",
        "pvtl/voyager-pages": "^0.2.9",
        "tcg/voyager": "^1.2"
    }
```
