### ISSUE TITLE
Error with file type field

### ISSUE THREAD

**Issue by Marycka9** [pvtl/voyager-page-blocks#23]
I created a file type field:

`        'file' => [
            'field' => 'file',
            'display_name' => 'PDF File',
            'partial' => 'voyager::formfields.file',
            'required' => 0
        ],`

When saving a file, the following error appears:

`Trying to get property 'download_link' of non-object (View: /var/www/vendor/tcg/voyager/resources/views/formfields/file.blade.php) (View: /var/www/vendor/tcg/voyager/resources/views/formfields/file.blade.php) (View: /var/www/vendor/tcg/voyager/resources/views/formfields/file.blade.php)
Previous exceptions
Trying to get property 'download_link' of non-object (View: /var/www/vendor/tcg/voyager/resources/views/formfields/file.blade.php) (View: /var/www/vendor/tcg/voyager/resources/views/formfields/file.blade.php) (0)
Trying to get property 'download_link' of non-object (View: /var/www/vendor/tcg/voyager/resources/views/formfields/file.blade.php) (0)
Trying to get property 'download_link' of non-object (0)`

In the file file.blade.php I found the cause of the error:

`Storage::disk(config('voyager.storage.disk'))->url($file->download_link) ?: ''`

$file->download_link it's a string, not an object.

I can correct this error in the file, but I do not think this is correct and the problem will appear every time the composer is updated.

What should I do with this error next?

-------------------------------------------

Tell me where you can read the documentation on all available fields and their options?

**Comment by Liam-PVTL** [comment]
Voyager's in-built fields won't _always_ be appropriate. 

Try changing your file type field to something like: ` 'file' => [ 'field' => 'file', 'display_name' => 'PDF File', 'partial' => 'formfields.custom_file', 'required' => 0 ] `

Then set up your own, custom form field in `resources/formfields/custom_file.blade.php` . 

This way you can avoid the properties / methods we don't supply. 

You can also modify the Blocks.php trait in your own branch to support file uploads that preserve the properties like 'download_link' and 'original_name' - here's a loosely adapted version from 'uploadImages' that might work for you (this will allow you to use the original file.blade.php from Voyager's src, minus the lines using ->getKey())

```
    public function uploadFiles(Request $request, array $data): array
    {
        $index = 0;
        foreach ($request->files as $key => $field) {
            if (is_array($request->file($key))) {
                $multiFiles = array();
                foreach ($request->file($key) as $key2 => $file) {
                    $filePath = $file->store('public/blocks');

                    $multiFiles[$index]['download_link'] = str_replace('public/', '', $filePath);
                    $multiFiles[$index]['original_name'] = $file->getClientOriginalName();
                }
                $data[$key] = json_encode($multiImages);
            } else {
                $filePath = $request->file($key)->store('public/blocks');
                $data[$key][$index]['download_link'] = str_replace('public/', '', $filePath);
                $data[$key][$index]['original_name'] = $field->getClientOriginalName();
            }
            $index++;
        }
        return $data;
    }
```
