### ISSUE TITLE
Can't upload photos via the (TinyMCE) 

### ISSUE THREAD

**Issue by shazimali** [pvtl/voyager-page-blocks#25]
why i can not insert photos from my computer for page block though (TinyMCE). Those, when adding a photo, nothing happens; it works only if I insert a link with a photo

**Screen short**
![image](https://user-images.githubusercontent.com/31865659/68765012-a2a95700-063d-11ea-9c78-422cb6509ea4.png)

**Comment by Liam-PVTL** [comment]
Hi Shazimali, this is a problem with Voyager's TinyMCE implementation. 

I've written a workaround in this thread I can see you are also following: https://github.com/the-control-group/voyager/issues/3914

**Comment by shazimali** [comment]
hi voyager page block team,

First of all i would like to thank you very much for solution, i used this solution in my custom file, but i am getting problem when i edit my page block.
In edit case if i need to add new page block then rich text editor field not showing, i think there is tinymce initialization problem, i am worried whats happening here i didn't understand. below i have attached related screen shots

already added  page block
![image](https://user-images.githubusercontent.com/31865659/70118051-e6194300-1688-11ea-9f25-8213a6b0e27d.png)


new added page block
![image](https://user-images.githubusercontent.com/31865659/70117396-355e7400-1687-11ea-9ea2-ef42fd7c2a2d.png)

you can see in above image rich text editor filed is missing
my custom js file code
function tinymce_init_callback(editor) {
    editor.remove();
    editor = null;

    tinymce.init({
        menubar: false,
        selector: 'textarea.richTextBox',
        skin_url: $('meta[name="assets-path"]').attr('content') + '?path=js/skins/voyager',
        min_height: 450,
        resize: 'vertical',
        plugins: 'link, image, code, table, textcolor, lists',
        extended_valid_elements: 'input[id|name|value|type|class|style|required|placeholder|autocomplete|onclick]',
        file_picker_callback: function (cb, value, meta) {
            var input = document.createElement('input');
            input.setAttribute('type', 'file');
            input.setAttribute('accept', 'image/*');
            input.onchange = function () {
                var file = this.files[0];

                var reader = new FileReader();
                reader.onload = function () {
                    var id = 'blobid' + (new Date()).getTime();
                    var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                    var base64 = reader.result.split(',')[1];
                    var blobInfo = blobCache.create(id, file, base64);
                    blobCache.add(blobInfo);

                    cb(blobInfo.blobUri(), {
                        title: file.name
                    });
                };
                reader.readAsDataURL(file);
            };

            input.click();
        },
        toolbar: 'styleselect bold italic underline | forecolor backcolor | alignleft aligncenter alignright | bullist numlist outdent indent | link image table | code',
        convert_urls: false,
        image_caption: false,
        image_title: true,
        image_class_list: [{
                title: 'None',
                value: ''
            },
            {
                title: 'Left',
                value: 'img-left'
            },
            {
                title: 'Center',
                value: 'img-center'
            },
            {
                title: 'Right',
                value: 'img-right'
            },
            {
                title: 'Image Right Column',
                value: 'img-column-right'
            }
        ],
        content_css: "/css/custom_tiny_mce.css?" + new Date().getTime() + "",
        force_br_newlines: true
    });
}
