### ISSUE TITLE
issue with viewing pages after install

### ISSUE THREAD

**Issue by johncarlson21** [pvtl/voyager-page-blocks#26]
getting this error in admin when I go to the pages section:

Facade\Ignition\Exceptions\ViewException
Missing required parameters for [Route: voyager.pages.destroy] [URI: admin/pages/{page}]. (View: /home/buzzlove/dev.buzzlove.me/vendor/pvtl/voyager-page-blocks/resources/views/vendor/voyager/pages/browse.blade.php) 

the issue comes from file: resources/views/vendor/voyager/pages/browse.blade.php:316

Laravel version
    6.8.0
Laravel locale
    en
Laravel config cached
    false
PHP version
    7.2.25

**Comment by johncarlson21** [comment]
also if I comment this out, then when I click on edit blocks it throws another error about Std::getKey() in an image partial file from voyager
/vendor/tcg/voyager/resources/views/formfields/image.blade.php
line 5

**Comment by DjeeBay** [comment]
Find the line `$('#delete_form')[0].action = '{{ route('voyager.'.$dataType->slug.'.destroy', ['id' => '__id']) }}'.replace('__id', $(this).data('id'));`

And replace it with `$('#delete_form')[0].action = '{{ route('voyager.'.$dataType->slug.'.destroy', ['page' => '__id']) }}'.replace('__id', $(this).data('id'));`

Did the trick for me.

**Comment by Liam-PVTL** [comment]
@johncarlson21  What version of Voyager & Laravel are you using? 6.8 has not currently been released, and we don't support 5.x versions anymore. 

Voyager uses {id} format instead of {page} in the latest release which we are also supporting. I'm closing for now as in a fresh install with this package the pages menu works correctly. (Laravel 6.2 Voyager 1.3)

**Comment by johncarlson21** [comment]
it was the last release.. you probably have a new version release now.. and laravel 6

**Comment by Liam-PVTL** [comment]
Hi John, can you provide steps to reproduce the problem & I'll happily re-open the issue
