### ISSUE TITLE
Extend View

### ISSUE THREAD

**Issue by Muzamel** [pvtl/voyager-page-blocks#27]
Hello, I am using this package's version:0.8.4, and have an issue when extended the view of add/edit blocks, from `vendor\pvtl\voyager-page-blocks\resources\views\vendor\voyager\page-blocks\edit-add.blade.php`. The view isn't extended, I followed the directory structure which defined [here](https://github.com/pvtl/voyager-page-blocks#2-build-the-html), but not succeeded. 
I need to extend the view for adding the image upload form with functionality,  which i found missing in the add/edit blocks.
Can anyone guide how to extend this view, or what I missed.
Thanks in advance.

**Comment by Liam-PVTL** [comment]
Hi @Muzamel, 
You need to create your own block under this directory:  `/resources/views/vendor/voyager-page-blocks/blocks/your_block.blade.php` as opposed to trying to extend the edit-add.blade.php file in the package.

It might help to follow the complete example [here](/resources/views/vendor/voyager-page-blocks/blocks/your_block.blade.php) if you're having trouble.

**Comment by Muzamel** [comment]
> Hi @Muzamel,
> You need to create your own block under this directory: `/resources/views/vendor/voyager-page-blocks/blocks/your_block.blade.php` as opposed to trying to extend the edit-add.blade.php file in the package.
> 
> It might help to follow the complete example [here](/resources/views/vendor/voyager-page-blocks/blocks/your_block.blade.php) if you're having trouble.

I try this thing according to the documentation and mentioned in my posted issue too. But it's not working for me.
Please read my posted issue, i added the documentation link, which i tried already.
And help for resolving this issue.

**Comment by Liam-PVTL** [comment]
Hi @Muzamel, I'm afraid there's not enough information here to help you. 

In your original comment you said you were attempting to create a file within the package itself, you need to create it under your projects directory, not the \vendor\pvtl\voyager-page-blocks project directory. From your comments this is the only help I can provide at this time.

**Comment by Muzamel** [comment]
No @Liam-PVTL  I tried "

> resources/views/vendor/voyager-page-blocks/blocks/your_block.blade.php

this as per documentation and mention the link in the line

>  I followed the directory structure which defined [here](https://github.com/pvtl/voyager-page-blocks#2-build-the-html), but not succeeded.

But extended view not working for me, after that I posted this issue.
Please see my posted issue again you will found the documentation link too, which I tried.
Thanks
