### ISSUE TITLE
Translatable Block Data

### ISSUE THREAD

**Issue by osmanzeki** [pvtl/voyager-page-blocks#3]
How would you go about translating the block data the way Voyager expects it? I'm sure this is not an easy task, but I would like to see if I can help or at least start the discussion on the subject.

**Comment by Jean-PierreGassin** [comment]
Hey @osmanzeki, glad to hear you'd like to help.

I'm sure this could be implemented with some i18n integration/wrapping for the output of blocks (check out how Voyager do it) with common words however I assume it won't be a completely accurate translation.

**Comment by osmanzeki** [comment]
I took a look at how other people do it in Voyager. On option seems to be to use their EAV-style `translations` table and add the complete content of the `data` field in there. Another option would be to have a `page_blocks_translations` adjacent table and handle it from there. That aspect seems pretty straightforward.

The aspects of showing the translation UI in the Page Blocks ui in Voyager is a little less clear to me as I don't have enough experience with the platform to understand how the UI does the toggle from one language to the other. I would have to take a deeper look at how that works before considering the approach in my opinion. If anyone in the community has an input on this, I'm interested in knowing more for sure.

**Comment by Jean-PierreGassin** [comment]
Definitely something I want to look into as well, I'm yet to discover translations with Voyager but from what I gather it seems fairly straight forward in regards to having the translation table and multilingual declaration on the DataType you wish to translate.

**Comment by osmanzeki** [comment]
I've taken a look at this and I haven't been able to find a way to use Voyager's builtin `translations` table yet. It seems like there are no mechanisms in Voyager to declare one of the block's dynamic fields (JSON fields) as translatable in the Eloquent model's `$translatable = ['data']` attribute.

Voyager seems to be storing the translated data in `hidden` input fields and when you select a language at the top right of the page using its default language selection UI, it toggles between the values found in every `hidden` field for every translatable field.

Since the page blocks' content fields cannot be declared in the `$translatable` attributes array as they are serialized as JSON in the `data` field, Voyager is not able to add the `hidden` data on a field-by-field basis as it expects.

One would have to parse the content of the `data` column and re-render the whole page/partial for each block in the selected language in order to be able to serialized and deserialized the content of the `data` attribute. This could probably be done by overriding the `vendor/tcg/voyager/src/Traits/Translatable.php` trait but I am not sure if the way the rendering of the CMS pages for Page Blocks is ready for something like this or if it would require a lot of changes overall.

Thoughts?

**Comment by Jean-PierreGassin** [comment]
You're right, you'd need to override the Translatable trait OR extend upon the underlying class to implement some new functionality with blocks.

I feel like translating the entire contents of a page block could become super cumbersome, especially the way that caching currently works.

You'd need to have a per-language basis cache which would then increase the size of the cache (although not by much).

Perhaps there's another way to re-render or even cache the content, maybe outsourcing the data contents to another source for non-primary languages.

Once again I'm not entirely sure on the best/most optimised approach to this but I'm really digging the suggestions.

**Comment by ElectroArmy** [comment]
I got this error when installing :(
$php artisan voyager-page-blocks:install
Publishing Page Blocks assets, database, and config files
Copied Directory [\vendor\pvtl\voyager-page-blocks\config] To [\config]
Publishing complete.
Dumping the autoloaded files and reloading all new files
Migrating the database tables into your application
Migrating: 2018_02_11_224531_create_page_blocks_table
Migrated:  2018_02_11_224531_create_page_blocks_table
Seeding data into the database

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'AlgoliaSearch\Version' not found

  at C:\xampp\htdocs\laravelapp\voyagerfullstack\vendor\laravel\scout\src\EngineManager.php:31
    27|      * @return \Laravel\Scout\Engines\AlgoliaEngine
    28|      */
    29|     public function createAlgoliaDriver()
    30|     {
  > 31|         AlgoliaUserAgent::addSuffixUserAgentSegment('Laravel Scout', '3.0.10');
    32|
    33|         return new AlgoliaEngine(new Algolia(
    34|             config('scout.algolia.id'), config('scout.algolia.secret')
    35|         ));

  Exception trace:

  1   Laravel\Scout\EngineManager::createAlgoliaDriver()
      C:\xampp\htdocs\laravelapp\voyagerfullstack\vendor\laravel\framework\src\Illuminate\Support\Manager.php:94

  2   Illuminate\Support\Manager::createDriver("algolia")
      C:\xampp\htdocs\laravelapp\voyagerfullstack\vendor\laravel\framework\src\Illuminate\Support\Manager.php:69

  Please use the argument -v to see more details.

**Comment by ThisIsJustARandomGuy** [comment]
I have tried and succeeded in extending (rewriting...) the Translatable trait and adding said functionality (including caches) to the package. However, I have done so in my project, so it'll take some time to extract the changes.

**Comment by rain2o** [comment]
I see this was closed, but I don't see any resolution. Was a solution for this every implemented, or a possible workaround? I'd love to be able to use this to improve our CMS experience in Voyager, but translations are a must-have.
