### ISSUE TITLE
Call to getKey on page block data which is not a class with getKey() 

### ISSUE THREAD

**Issue by salvationws** [pvtl/voyager-page-blocks#30]
Hello, can, canOrFail and canOrAbort have been deprecated in voyager.

![image](https://user-images.githubusercontent.com/16476638/73642867-eedbc480-468b-11ea-9b04-89bf16aef4c2.png)

**Comment by salvationws** [comment]
$dataTypeContent->id was changed to $dataTypeContent->$dataTypeContent->getKey(). But only editing this does not helps

**Comment by Liam-PVTL** [comment]
Thanks for opening this issue @salvationws. I'm not sure what you were referencing in your last title (which I have now modified), but the new title & bug that was mentioned in your description is fixed.
