### ISSUE TITLE
Invalid argument supplied for foreach() on MockedModel.php

### ISSUE THREAD

**Issue by Mabudigital** [pvtl/voyager-page-blocks#31]
I'm getting this error when try to add blocks on a new page.

Facade\Ignition\Exceptions\ViewException
Invalid argument supplied for foreach() (View: C:\xampp\htdocs\mysite\vendor\pvtl\voyager-page-blocks\resources\views\vendor\voyager\page-blocks\edit-add.blade.php) 

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
C:\xampp\htdocs\mysite\vendor\pvtl\voyager-page-blocks\src\MockedModel.php:10

**Comment by Liam-PVTL** [comment]
Thanks to both of you. This is fixed in 0.8.16.
