### ISSUE TITLE
Error when add a developer controller block

### ISSUE THREAD

**Issue by thieuns88** [pvtl/voyager-page-blocks#32]
I get error when add Developer Controller Block:
"Invalid argument supplied for foreach() (View: ...\vendor\pvtl\voyager-page-blocks\resources\views\vendor\voyager\page-blocks\edit-add.blade.php)"
Can you help me?

**Comment by Liam-PVTL** [comment]
Thanks for the report @thieuns88. This has been fixed in 0.8.16.
