### ISSUE TITLE
Issue with editing page blocks

### ISSUE THREAD

**Issue by samitray-at-consultree** [pvtl/voyager-page-blocks#36]
Creating page block content from the Voyager admin is fine but when I am trying to edit after saving them, it is not showing the old data. The blocks come with blank data and if saved, the database table (page_blocks) is also updated with blank data.

**Comment by OpJePl44tsm4n** [comment]
i've got the same problem since last updates form 0.8.15 -> 0.8.16, the saved content is not loaded in the admin edit page.
Reverting back to 0.8.15 solved it for now.

**Comment by jaromic** [comment]
@Liam-PVTL @OpJePl44tsm4n we manually merged that PR and it solves the problem for us

**Comment by Liam-PVTL** [comment]
Thank you all, I've merged this in to master & released it on 0.8.17
