### ISSUE TITLE
Undefined index: type for fields

### ISSUE THREAD

**Issue by johncarlson21** [pvtl/voyager-page-blocks#42]
commit: 376dc46

I'm having a problem with this as this did not fix it.
if a field does not have a 'type'  in the array it will throw an error.

`ErrorException
Undefined index: type (View: /home/xxxxxxxx/xxxxxxxxx/vendor/pvtl/voyager-page-blocks/resources/views/vendor/voyager/page-blocks/edit-add.blade.php) `

this happens on all the br_* fields I actually think this check should be on the 'partial' element in the array

`'br_1' => [
            'field' => 'br_1',
            'display_name' => 'Line Break',
            'partial' => 'break',
        ],`

**Comment by johncarlson21** [comment]
Actually on the file: vendor/pvtl/voyager-page-blocks/src/PageBlock.php around line 83, this is what works.

                if (isset($row['partial']) && $row['partial'] === 'break') {
                    $row['type'] = 'break';
                    return (object)$row;
                }
```

**Comment by gisminero** [comment]
> if (isset($row['partial']) && $row['partial'] === 'break') {
>                 $row['type'] = 'break';
>                 return (object)$row;
>             }

Thanks you so much! This works for me!

**Comment by lukewmoore** [comment]
This has now been fixed with https://github.com/pvtl/voyager-page-blocks/pull/41/commits/cfbfa34651a88fed458fa7aa1525ca228e56a961
