### ISSUE TITLE
Default installation will not display images in page blocks

### ISSUE THREAD

**Issue by ajduff14** [pvtl/voyager-page-blocks#43]
Hi,

Firstly great product, really looking forward to getting to use it & know it more.

I've noticed that when I upload images to a page block they do not display & they upload my images to public/storage/public/blocks/(myimage).jpg

Here is the actual filepath of an upload. http://mysite.test/storage/public/blocks/sj6CJ28kOWxdbBuHX4QWrh5N5pvE7zDlbWllXl12.jpeg

My filesystems.php is the default settings for laravel 7 & I can upload and view images perfectly fine for Laravel Voyager.

I have the following dependencies...
`        "php": "^7.3",
        "ext-bread-fields-fix": "dev-master",
        "ext-json": "*",
        "algolia/algoliasearch-client-php": "^2.7",
        "bugsnag/bugsnag-laravel": "^2.0",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/ui": "^2.0",
        "pvtl/voyager-blog": "^0.2.9",
        "pvtl/voyager-forms": "^0.4.7",
        "pvtl/voyager-frontend": "^0.9.8",
        "pvtl/voyager-page-blocks": "^0.9.0",
        "tcg/voyager": "^1.4"`

This is the filesystem driver set in .env file
`FILESYSTEM_DRIVER=public`

Any support or guidance would be much appreciated!

Adam

**Comment by johncarlson21** [comment]
remove this: FILESYSTEM_DRIVER=public

**Comment by ajduff14** [comment]
This worked perfectly thanks! Not as default installation as I thought.
