### ISSUE TITLE
TinyMCE no upload images in blocks

### ISSUE THREAD

**Issue by johncarlson21** [pvtl/voyager-page-blocks#44]
I'm using laravel 7.28.x and all the latest voyager packages.
TinyMCE upload works just fine in bread rich text boxes, but it does not in blocks.

something is not triggering or loading the same.
there are no errors in console etc.

**Comment by lukewmoore** [comment]
The Voyager upload form was missing from the `edit-add.blade.php` view. This has been fixed as of version `0.10.1`.
