### ISSUE TITLE
Field options for image

### ISSUE THREAD

**Issue by zeroiszero** [pvtl/voyager-page-blocks#9]
can i confirm there is no resize/thumbnail generation for the field option, right ?

like the one is voyager
https://voyager.readme.io/docs/additional-field-options

**Comment by lukewmoore** [comment]
@zeroiszero No there's not. There is however a helper function that generates thumbnails in blade templates.
```php
# output thumbnail 200px by 100px 
{{ imageUrl('/path/to/image', 200, 100) }}

# output thumbnail scaled to 320px wide
{{ imageUrl('/path/to/image', 320, null, ['crop' => false]) }}
```
If the thumbnail doesn't exist, it will be created on the fly.
